---
- name: Get required packages
  ansible.builtin.apt:
    name: 
      - gnupg2
      - curl 
    state: present

- name: Add the GPG key
  ansible.builtin.shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg

- name: Add the agent repo the sources
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
    state: present

- name: Refresh APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Run Wazuh install command
  ansible.builtin.shell: WAZUH_MANAGER="{{ wazuh_server }}" apt-get install wazuh-agent
