network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: yes
      # addresses:
      #   - 192.168.121.221/24
      # gateway4: 192.168.121.1
      # nameservers:
      #     addresses: [8.8.8.8, 1.1.1.1]
      #     search: [local.uaccloud.com]