network:
  version: 2
  renderer: networkd
  ethernets:
    ens33:
      link-local: [ ipv4 ]
      addresses:
        - "{{ ip-addr }}"
      routes:
       - to: 0.0.0.0/0
         via: "{{ gateway }}"
      nameservers:
          addresses: "{{ dns-servers }}"
          search: "{{ search-domain }}"
