---
- name: Update yum cache
  yum:
    update_cache: true
  become: true

- name: Upgrade all packages with yum
  yum:
    name: "*"
    state: latest
  become: true

- name: Remove all unused dependencies with yum
  yum:
    autoremove: true
  become: true
