---

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Update sshd configuration safely, avoid locking yourself out
  ansible.builtin.template:
    src: sshd_config
    dest: /etc/ssh/sshd_config.d/uac_sshd_conf.conf
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  become: true
  notify: Restart sshd

- name: Set timezone to US Pacific time
  community.general.timezone:
    name: America/Los_Angeles
  become: true

- name: Update Message of the Day
  ansible.builtin.template:
    src: motd
    dest: /etc/motd
    owner: root
    group: root
    mode: '0600'
    backup: true
  become: true

- name: Reboot and check that is up with uptime command
  ansible.builtin.reboot:
    reboot_timeout: 180
    boot_time_command: uptime
  become: true

- name: Register with Red Hat, set syspurpose attributes and synchronize them with server
  community.general.redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password}}"
    auto_attach: true
    syspurpose:
      usage: "Production"
      role: "Red Hat Enterprise Server"
      service_level_agreement: "Self Supported"
      sync: true
  become: true
