---

- name: Register with Red Hat, set syspurpose attributes and synchronize them with server
  community.general.redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password}}"
    auto_attach: true
    syspurpose:
      usage: "Production"
      role: "Red Hat Enterprise Server"
      service_level_agreement: "Self Supported"
      sync: true

- name: Update sshd configuration safely, avoid locking yourself out
  ansible.builtin.template:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config.d/uac_sshd_conf.conf
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: Restart sshd

- name: Set timezone to US Pacific time
  community.general.timezone:
    name: America/Los_Angeles

- name: Update Message of the Day
  ansible.builtin.template:
    src: templates/motd
    dest: /etc/motd
    owner: root
    group: root
    mode: '0600'
    backup: true
