---
- name: Run the equivalent of "apt update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Upgrade the OS (apt dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot the box if needed
  reboot:
    msg: "Reboot initiated by AWX for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists