---
- name: Update dnf cache
  dnf:
    update_cache: true
  become: true

- name: Upgrade all packages with dnf
  dnf:
    name: "*"
    state: latest
  become: true

- name: Remove all unused dependencies with dnf
  dnf:
    autoremove: true
  become: true

- name: Reboot the box
  reboot:
    msg: "Reboot initiated by AWX for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    post_reboot_delay: 30
    test_command: uptime
  become: true
